Adding HomeworkLesson2
AleksandrKostinJava/GeekBrainsStudy pull request #2
Opened 2020-12-11 08:34 UTC by AleksandrKostinJava

2020-12-13 07:50 UTC, OKrylov requested changes
Все отлично, кроме последнего задания, обратите внимание на замечание

2020-12-13 07:50 UTC, OKrylov commented on HomeworkLesson2.java
> +            arr[i] = number;
можно заменить на `arr[i] = i * 3;`

2020-12-13 07:50 UTC, OKrylov commented on HomeworkLesson2.java
> +//          Arrays.sort(arr);
тоже рабочий вариант, но если массив очень большой, то один цикл выше эффективнее целой сортировки

2020-12-13 07:50 UTC, OKrylov commented on HomeworkLesson2.java
> +            if (overallSum - leftSum == 0) {
но ведь в таком случае нужно вычитать на каждой итерации из общей суммы те элементы, что мы включаем в левую часть

2020-12-13 18:32 UTC, AleksandrKostinJava reviewed
Здравствуйте. Исправил ошибку и учел замечания. Надеюсь все сделал правильно в гитхабе и изменения будут понятны.

2020-12-13 18:32 UTC, AleksandrKostinJava commented on HomeworkLesson2.java
> +            if (overallSum - leftSum == 0) {
```suggestion
            if (leftSum == overallSum - leftSum {
```

2020-12-13 18:32 UTC, AleksandrKostinJava commented on HomeworkLesson2.java
> +            number += 3;
```suggestion
```

2020-12-13 18:32 UTC, AleksandrKostinJava commented on HomeworkLesson2.java
> +            arr[i] = number;
```suggestion
            arr[i] = i * 3;
```

2020-12-13 18:32 UTC, AleksandrKostinJava commented on HomeworkLesson2.java
> +        int number = 0;
```suggestion
      
```

2020-12-13 18:40 UTC, AleksandrKostinJava commented on HomeworkLesson2.java
> +            if (leftSum == overallSum - leftSum {
fixed

2020-12-27 18:33 UTC, OKrylov approved these changes
По ДЗ все отлично, замечаний нет

2021-01-16 09:52 UTC, closed without merging